#!/usr/bin/env python3
"""
Run ML analyses on the Olist gold DuckDB warehouse.

  cd data-warehouse
  python -m ml.run_ml
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

_DW_ROOT = Path(__file__).resolve().parent.parent
if str(_DW_ROOT) not in sys.path:
    sys.path.insert(0, str(_DW_ROOT))

from pipeline.config import DEFAULT_DUCKDB_PATH, REPO_ROOT  # noqa: E402
from pipeline.db import connect_duckdb  # noqa: E402

from ml.rfm_segmentation import run_rfm_segmentation  # noqa: E402


def setup_logging(verbose: bool = False) -> None:
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s | %(levelname)-7s | %(name)s | %(message)s",
        datefmt="%H:%M:%S",
    )


def export_results(payload: dict, repo_root: Path = REPO_ROOT) -> list[Path]:
    """Write JSON (+ JS mirror) under js/ for GitHub Pages."""
    js_dir = repo_root / "js"
    js_dir.mkdir(parents=True, exist_ok=True)
    assets = repo_root / "assets" / "data"
    assets.mkdir(parents=True, exist_ok=True)

    body = json.dumps(payload, ensure_ascii=False, indent=2, default=str)
    paths = []
    for folder in (js_dir, assets):
        p = folder / "ml_results.json"
        p.write_text(body, encoding="utf-8")
        paths.append(p)
        js_p = folder / "ml_results.js"
        js_p.write_text(
            "/* auto-generated by ml.run_ml — do not edit */\n"
            "window.__OLIST_ML__ = "
            + json.dumps(payload, ensure_ascii=False, default=str)
            + ";\n",
            encoding="utf-8",
        )
        paths.append(js_p)
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Olist ML: RFM customer segmentation")
    parser.add_argument(
        "--duckdb",
        type=Path,
        default=DEFAULT_DUCKDB_PATH,
        help="Path to olist_dw.duckdb",
    )
    parser.add_argument("--k", type=int, default=None, help="Force KMeans k (default: auto)")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)
    setup_logging(args.verbose)
    log = logging.getLogger("ml")

    if not args.duckdb.is_file():
        log.error(
            "DuckDB not found: %s\nRun: python -m pipeline.run",
            args.duckdb,
        )
        return 2

    log.info("Opening %s (read-only)", args.duckdb)
    con = connect_duckdb(args.duckdb, read_only=True)
    try:
        rfm = run_rfm_segmentation(con, k=args.k)
    finally:
        con.close()

    payload = {
        "meta": {
            "project": "Olist RFM Customer Segmentation",
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "source": "gold.fact_order + dim_customer + dim_date",
            "duckdb": str(args.duckdb.name),
        },
        "rfm_segmentation": rfm,
    }

    paths = export_results(payload)
    for p in paths:
        log.info("Wrote %s (%.1f KB)", p, p.stat().st_size / 1024)

    # Console summary
    print("\n=== RFM Segmentation Summary ===")
    print(f"Customers : {rfm['n_customers']:,}")
    print(f"k         : {rfm['k']}")
    print(f"Snapshot  : {rfm['snapshot_date']}")
    print("\n--- Evaluation metrics (final model) ---")
    print(f"  Silhouette (↑ better)     : {rfm.get('silhouette')}")
    print(f"  Davies-Bouldin (↓ better) : {rfm.get('davies_bouldin')}")
    print(f"  Calinski-Harabasz (↑)     : {rfm.get('calinski_harabasz')}")
    print(f"  Inertia / SSE (↓)         : {rfm.get('inertia')}")
    by_k = (rfm.get("evaluation") or {}).get("by_k") or []
    if by_k:
        print("\n--- Metrics by k (model selection) ---")
        print(f"  {'k':>3}  {'Sil':>8}  {'DBI':>8}  {'CHI':>10}  {'Inertia':>12}")
        for row in by_k:
            print(
                f"  {row['k']:>3}  {row['silhouette']:8.4f}  {row['davies_bouldin']:8.4f}  "
                f"{row['calinski_harabasz']:10.1f}  {row['inertia']:12.1f}"
            )
    print("\nSegments:")
    for s in rfm["segments"]:
        sil_c = s.get("silhouette_mean")
        sil_s = f"{sil_c:.3f}" if sil_c is not None else "n/a"
        print(
            f"  {s['segment']:28s}  n={s['size']:>6,} ({s['pct']:5.1f}%)  "
            f"R̄={s['recency_mean']:6.1f}d  F̄={s['frequency_mean']:5.2f}  "
            f"M̄={s['monetary_mean']:8.1f}  GMV%={s['gmv_share_pct']:5.1f}  "
            f"sil={sil_s}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
